name: Linux build

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}//Build-Linux

    - name: Update env
      run: sudo apt-get update -y

    - name: Check env 0
      run: gcc -v

    - name: Update gcc
      run: sudo apt install g++ g++-9 gcc && sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 800 --slave /usr/bin/g++ g++ /usr/bin/g++-9

    - name: Check env 1
      run: gcc -v

    - name: Install Linux prequisities
      run: sudo apt install mesa-common-dev libxi-dev libglu1-mesa-dev

    - name: Prepare fetch
      uses: MrSquaare/ssh-setup-action@v1
      with:
        host: github.com
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Fetch dependencies - begin
      shell: bash
      working-directory: ${{github.workspace}}
      env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: time git submodule update --recursive --init && find . -name '*.git'

    - name: Fetch dependencies - second
      shell: bash
      working-directory: ${{github.workspace}}
      env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: time git submodule update --recursive --init && find . -name '*.git'

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/Build-Linux
      # Note the current convention is to use the -S and -B options here to specify source
      # and build directories, but this is only available with CMake 3.13 and higher.
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: time cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${BUILD_TYPE}

    - name: Build static
      working-directory: ${{github.workspace}}//Build-Linux
      shell: bash
      run: cmake --build . --config ${BUILD_TYPE} -j16 --target libsdl2wrapperTestApp_static

    - name: Build dynamic
      working-directory: ${{github.workspace}}//Build-Linux
      shell: bash
      run: cmake --build . --config ${BUILD_TYPE} -j16 --target libsdl2wrapperTestApp_dynamic